# Build targets for the lyrics server binary and OBS plugin across platforms.
# Suitable for local use and CI. All outputs land in the project root.
#
# Common targets:
#   make build-binary-linux-amd64        lyrics server binary, Linux/amd64
#   make build-binary-windows-amd64      lyrics server binary, Windows/amd64
#   make build-plugin-linux-amd64        OBS plugin .so, Linux/amd64 (native CGO)
#   make build-plugin-linux-arm64        OBS plugin .so, Linux/arm64 (native CGO)
#   make build-plugin-windows-amd64      OBS plugin .dll, Windows/amd64 (MinGW cross-compile)
#   make clean                           clean all build outputs
#   make clean-plugin-windows-amd64      clean only Windows plugin outputs (incl. OBS SDK)

VERSION     ?= $(shell git describe --always --tags 2>/dev/null || echo dev)
PE_VERSION  ?= $(shell (git describe --always --tags --long 2>/dev/null || echo 0.0.0-0) | sed 's/^v//; s/-g.*//' | awk -F'-' '{printf "%s.%s", $$1, $$2}')
OBS_VERSION ?= 32.1.2
GITHUB_REPO ?= icedream/obs-spotify-lyrics
MAKENSIS    ?= makensis

# Set UPX= to the upx binary (e.g. make UPX=upx ...) to enable optional
# compression of standalone binaries after stripping. Disabled by default.
# Plugin .so/.dll files are intentionally excluded: shared libraries loaded via
# dlopen/LoadLibrary are incompatible with UPX's entry-point wrapping.
UPX ?=

OBS_WIN_SRC := obs-src
OBS_WIN_SDK := obs-win-sdk

.PHONY: all
all: build-binary-linux-amd64 build-binary-linux-arm64 build-binary-windows-amd64 build-binary-windows-arm64 build-plugin-linux-amd64 build-plugin-linux-arm64 build-plugin-windows-amd64 build-installer-windows-amd64

###############################################################################
# Binary

.PHONY: build-binary-linux-amd64
build-binary-linux-amd64:
	GOOS=linux   GOARCH=amd64 CGO_ENABLED=0 go build \
		-trimpath \
		-ldflags "-s -w -X main.version=$(VERSION)" \
		-o lyrics-linux-amd64 ./cmd/lyrics/
	$(if $(UPX),$(UPX) --lzma lyrics-linux-amd64)

.PHONY: build-binary-linux-arm64
build-binary-linux-arm64:
	GOOS=linux   GOARCH=arm64 CGO_ENABLED=0 go build \
		-trimpath \
		-ldflags "-s -w -X main.version=$(VERSION)" \
		-o lyrics-linux-arm64 ./cmd/lyrics/
	$(if $(UPX),$(UPX) --lzma lyrics-linux-arm64)

cmd/lyrics/gen_resource_windows_amd64.syso cmd/lyrics/gen_resource_windows_arm64.syso &: cmd/lyrics/versioninfo.json assets/icon.ico Makefile
	go tool goversioninfo -64      -file-version "$(PE_VERSION)" -product-version "$(PE_VERSION)" -icon assets/icon.ico -o cmd/lyrics/gen_resource_windows_amd64.syso cmd/lyrics/versioninfo.json
	go tool goversioninfo -64 -arm -file-version "$(PE_VERSION)" -product-version "$(PE_VERSION)" -icon assets/icon.ico -o cmd/lyrics/gen_resource_windows_arm64.syso cmd/lyrics/versioninfo.json

.PHONY: build-binary-windows-amd64
build-binary-windows-amd64: cmd/lyrics/gen_resource_windows_amd64.syso
	GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build \
		-trimpath \
		-ldflags "-s -w -X main.version=$(VERSION)" \
		-o lyrics-windows-amd64.exe ./cmd/lyrics/
	$(if $(UPX),$(UPX) --lzma lyrics-windows-amd64.exe)

.PHONY: build-binary-windows-arm64
build-binary-windows-arm64: cmd/lyrics/gen_resource_windows_arm64.syso
	GOOS=windows GOARCH=arm64 CGO_ENABLED=0 go build \
		-trimpath \
		-ldflags "-s -w -X main.version=$(VERSION)" \
		-o lyrics-windows-arm64.exe ./cmd/lyrics/

###############################################################################
# OBS plugin

.PHONY: build-plugin-linux-amd64
build-plugin-linux-amd64:
	$(MAKE) -C plugin \
		PLUGIN_SO="$(CURDIR)/spotify-lyrics-linux-amd64.so" \
		VERSION="$(VERSION)" \
		GITHUB_REPO="$(GITHUB_REPO)"

.PHONY: build-plugin-linux-arm64
build-plugin-linux-arm64:
	$(MAKE) -C plugin \
		PLUGIN_SO="$(CURDIR)/spotify-lyrics-linux-arm64.so" \
		VERSION="$(VERSION)" \
		GITHUB_REPO="$(GITHUB_REPO)"

$(OBS_WIN_SRC)/.stamp:
	git clone --filter=blob:none --no-checkout --depth=1 \
		--branch "$(OBS_VERSION)" \
		https://github.com/obsproject/obs-studio.git $(OBS_WIN_SRC)
	cd $(OBS_WIN_SRC) && \
		git sparse-checkout init --cone && \
		git sparse-checkout set libobs frontend/api && \
		git checkout
	# obsconfig.h is generated by CMake at build time; produce a minimal
	# Windows-safe version from the in-tree template.
	sed \
		-e 's|^#cmakedefine \([^ ]*\).*|/* #undef \1 */|' \
		-e 's|@OBS_RELEASE_CANDIDATE@|0|g' \
		-e 's|@OBS_BETA@|0|g' \
		$(OBS_WIN_SRC)/libobs/obsconfig.h.in > $(OBS_WIN_SRC)/libobs/obsconfig.h
	touch $@

$(OBS_WIN_SDK)/.stamp:
	wget -q \
		"https://github.com/obsproject/obs-studio/releases/download/$(OBS_VERSION)/OBS-Studio-$(OBS_VERSION)-Windows-x64.zip" \
		-O obs-win.zip
	unzip -q obs-win.zip -d obs-win-tmp
	mkdir -p $(OBS_WIN_SDK)
	find obs-win-tmp -name obs.dll             -exec cp {} $(OBS_WIN_SDK)/obs.dll \;
	find obs-win-tmp -name obs-frontend-api.dll -exec cp {} $(OBS_WIN_SDK)/obs-frontend-api.dll \;
	rm -rf obs-win-tmp obs-win.zip
	cd $(OBS_WIN_SDK) && \
		gendef obs.dll && \
		x86_64-w64-mingw32-dlltool -d obs.def             -l libobs.dll.a && \
		gendef obs-frontend-api.dll && \
		x86_64-w64-mingw32-dlltool -d obs-frontend-api.def -l libobs-frontend-api.dll.a
	touch $@

.PHONY: build-plugin-windows-amd64
build-plugin-windows-amd64: $(OBS_WIN_SRC)/.stamp $(OBS_WIN_SDK)/.stamp
	GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc \
		CGO_CFLAGS="-I$(CURDIR)/$(OBS_WIN_SRC)/libobs -I$(CURDIR)/$(OBS_WIN_SRC)/frontend/api" \
		CGO_LDFLAGS="-L$(CURDIR)/$(OBS_WIN_SDK) -lobs -lobs-frontend-api" \
		go build -buildmode=c-shared \
		-trimpath \
		-ldflags "-s -w -X main.pluginVersion=$(VERSION) -X main.githubReleasesURL=https://api.github.com/repos/$(GITHUB_REPO)/releases/latest" \
		-o spotify-lyrics-windows-amd64.dll ./plugin/

.PHONY: build-installer-windows-amd64
build-installer-windows-amd64: build-binary-windows-amd64 build-plugin-windows-amd64
	$(MAKENSIS) -DVERSION=$(VERSION) installer/spotify-lyrics.nsi

.PHONY: package-installer-windows-amd64
package-installer-windows-amd64:
	$(MAKENSIS) -DVERSION=$(VERSION) installer/spotify-lyrics.nsi

###############################################################################
# Cleanup
.PHONY: clean
clean: clean-binary-linux-amd64 clean-binary-linux-arm64 \
       clean-binary-windows-amd64 clean-binary-windows-arm64 \
       clean-plugin-linux-amd64 clean-plugin-linux-arm64 \
       clean-plugin-windows-amd64 clean-installer-windows-amd64

.PHONY: clean-binary-linux-amd64
clean-binary-linux-amd64:
	rm -f lyrics-linux-amd64

.PHONY: clean-binary-linux-arm64
clean-binary-linux-arm64:
	rm -f lyrics-linux-arm64

.PHONY: clean-binary-windows-amd64
clean-binary-windows-amd64:
	rm -f lyrics-windows-amd64.exe cmd/lyrics/gen_resource_windows_amd64.syso

.PHONY: clean-binary-windows-arm64
clean-binary-windows-arm64:
	rm -f lyrics-windows-arm64.exe cmd/lyrics/gen_resource_windows_arm64.syso

.PHONY: clean-plugin-linux-amd64
clean-plugin-linux-amd64:
	rm -f spotify-lyrics-linux-amd64.so spotify-lyrics-linux-amd64.h

.PHONY: clean-plugin-linux-arm64
clean-plugin-linux-arm64:
	rm -f spotify-lyrics-linux-arm64.so spotify-lyrics-linux-arm64.h

.PHONY: clean-plugin-windows-amd64
clean-plugin-windows-amd64:
	rm -f spotify-lyrics-windows-amd64.dll spotify-lyrics-windows-amd64.h
	rm -rf $(OBS_WIN_SRC) $(OBS_WIN_SDK) obs-win.zip obs-win-tmp

.PHONY: clean-installer-windows-amd64
clean-installer-windows-amd64:
	rm -f obs-spotify-lyrics-*-setup.exe
